# Generated by Django 3.1.6 on 2021-03-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='desc',
        ),
    ]
