# Generated by Django 3.1.6 on 2021-03-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0002_auto_20210307_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FUll_Name',
            new_name='Full_Name',
        ),
    ]
