# Generated by Django 3.1.6 on 2021-03-08 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0003_auto_20210307_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Full_Name',
            new_name='name',
        ),
    ]
