# Generated by Django 3.1.6 on 2021-03-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest', '0004_auto_20210308_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Event_Name',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Full_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Phone_No',
            new_name='phone',
        ),
    ]
